// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Appointment struct {
	ID                    pgtype.UUID        `json:"id"`
	ProfileID             pgtype.UUID        `json:"profile_id"`
	CustomerID            pgtype.UUID        `json:"customer_id"`
	SpecialistID          pgtype.UUID        `json:"specialist_id"`
	Title                 string             `json:"title"`
	Description           pgtype.Text        `json:"description"`
	StartDatetime         pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime           pgtype.Timestamptz `json:"end_datetime"`
	Status                string             `json:"status"`
	Price                 pgtype.Float8      `json:"price"`
	Notes                 pgtype.Text        `json:"notes"`
	CustomFields          []byte             `json:"custom_fields"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	IsDeleted             pgtype.Bool        `json:"is_deleted"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	Paid                  pgtype.Bool        `json:"paid"`
	PetID                 pgtype.UUID        `json:"pet_id"`
	AppointmentType       pgtype.Text        `json:"appointment_type"`
	PreliminaryDiagnosis  pgtype.Text        `json:"preliminary_diagnosis"`
	RecommendationsBefore pgtype.Text        `json:"recommendations_before"`
}

type Certificate struct {
	ID                pgtype.UUID        `json:"id"`
	ProfileID         pgtype.UUID        `json:"profile_id"`
	EventID           pgtype.UUID        `json:"event_id"`
	RegistrationID    pgtype.UUID        `json:"registration_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CertificateType   pgtype.Text        `json:"certificate_type"`
	RecipientName     string             `json:"recipient_name"`
	CertificateNumber pgtype.Text        `json:"certificate_number"`
	VerificationCode  pgtype.Text        `json:"verification_code"`
	PdfUrl            pgtype.Text        `json:"pdf_url"`
	IsIssued          pgtype.Bool        `json:"is_issued"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CoreAccount struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	Username     pgtype.Text        `json:"username"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	Tg           pgtype.Text        `json:"tg"`
	Phone        pgtype.Text        `json:"phone"`
	Vk           pgtype.Text        `json:"vk"`
	Role         pgtype.Text        `json:"role"`
	Perms        pgtype.Text        `json:"perms"`
	Active       pgtype.Bool        `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Archived     pgtype.Bool        `json:"archived"`
	RoleID       pgtype.UUID        `json:"role_id"`
}

type CoreModule struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	Icon            pgtype.Text        `json:"icon"`
	IsCore          pgtype.Bool        `json:"is_core"`
	RequiresModules []string           `json:"requires_modules"`
	SettingsSchema  []byte             `json:"settings_schema"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CorePermission struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CoreProfile struct {
	ID                       pgtype.UUID        `json:"id"`
	Active                   pgtype.Bool        `json:"active"`
	Domain                   pgtype.Text        `json:"domain"`
	Email                    pgtype.Text        `json:"email"`
	Firstname                pgtype.Text        `json:"firstname"`
	Lastname                 pgtype.Text        `json:"lastname"`
	Patronymic               pgtype.Text        `json:"patronymic"`
	IsBusinessOwner          pgtype.Bool        `json:"is_business_owner"`
	IsBusinessAdmin          pgtype.Bool        `json:"is_business_admin"`
	Extra                    pgtype.Text        `json:"extra"`
	Archived                 pgtype.Bool        `json:"archived"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	CompanyName              pgtype.Text        `json:"company_name"`
	BusinessType             pgtype.Text        `json:"business_type"`
	Inn                      pgtype.Text        `json:"inn"`
	Ogrn                     pgtype.Text        `json:"ogrn"`
	Kpp                      pgtype.Text        `json:"kpp"`
	Okpo                     pgtype.Text        `json:"okpo"`
	AccountNumber            pgtype.Text        `json:"account_number"`
	BankBic                  pgtype.Text        `json:"bank_bic"`
	BankCorrespondentAccount pgtype.Text        `json:"bank_correspondent_account"`
	BankInn                  pgtype.Text        `json:"bank_inn"`
	BankName                 pgtype.Text        `json:"bank_name"`
	BankAddress              pgtype.Text        `json:"bank_address"`
	ContactPerson            pgtype.Text        `json:"contact_person"`
	ContactPhone             pgtype.Text        `json:"contact_phone"`
	ContactTelegram          pgtype.Text        `json:"contact_telegram"`
	LegalAddress             pgtype.Text        `json:"legal_address"`
	ActualAddress            pgtype.Text        `json:"actual_address"`
	Tariff                   pgtype.Text        `json:"tariff"`
	WorkStartDate            pgtype.Date        `json:"work_start_date"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type CoreProfileModule struct {
	ID        pgtype.UUID        `json:"id"`
	ProfileID pgtype.UUID        `json:"profile_id"`
	ModuleID  pgtype.UUID        `json:"module_id"`
	Enabled   pgtype.Bool        `json:"enabled"`
	Settings  []byte             `json:"settings"`
	EnabledAt pgtype.Timestamptz `json:"enabled_at"`
	EnabledBy pgtype.UUID        `json:"enabled_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CoreRole struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CoreRolePermission struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Credential struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	Name           string             `json:"name"`
	CredentialType string             `json:"credential_type"`
	Description    pgtype.Text        `json:"description"`
	Key1           pgtype.Text        `json:"key1"`
	Key2           pgtype.Text        `json:"key2"`
	Key3           pgtype.Text        `json:"key3"`
	Metadata       []byte             `json:"metadata"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CustomField struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	EntityType string             `json:"entity_type"`
	FieldKey   string             `json:"field_key"`
	FieldLabel string             `json:"field_label"`
	FieldType  string             `json:"field_type"`
	Options    []byte             `json:"options"`
	Required   pgtype.Bool        `json:"required"`
	OrderIndex pgtype.Int4        `json:"order_index"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
}

type Customer struct {
	ID                pgtype.UUID        `json:"id"`
	ProfileID         pgtype.UUID        `json:"profile_id"`
	CustomerType      string             `json:"customer_type"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Website           pgtype.Text        `json:"website"`
	AddressCountry    pgtype.Text        `json:"address_country"`
	AddressRegion     pgtype.Text        `json:"address_region"`
	AddressCity       pgtype.Text        `json:"address_city"`
	AddressStreet     pgtype.Text        `json:"address_street"`
	AddressPostalCode pgtype.Text        `json:"address_postal_code"`
	CompanyName       pgtype.Text        `json:"company_name"`
	Inn               pgtype.Text        `json:"inn"`
	Kpp               pgtype.Text        `json:"kpp"`
	Ogrn              pgtype.Text        `json:"ogrn"`
	LegalAddress      pgtype.Text        `json:"legal_address"`
	Source            pgtype.Text        `json:"source"`
	Status            pgtype.Text        `json:"status"`
	Priority          pgtype.Text        `json:"priority"`
	Tags              []string           `json:"tags"`
	Notes             pgtype.Text        `json:"notes"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	IsDeleted         pgtype.Bool        `json:"is_deleted"`
	AccountID         pgtype.UUID        `json:"account_id"`
}

type CustomerVkLink struct {
	ID                   pgtype.UUID        `json:"id"`
	ProfileID            pgtype.UUID        `json:"profile_id"`
	CustomerID           pgtype.UUID        `json:"customer_id"`
	VkID                 int64              `json:"vk_id"`
	VkFirstName          pgtype.Text        `json:"vk_first_name"`
	VkLastName           pgtype.Text        `json:"vk_last_name"`
	VkPhotoUrl           pgtype.Text        `json:"vk_photo_url"`
	NotificationsEnabled pgtype.Bool        `json:"notifications_enabled"`
	LinkedAt             pgtype.Timestamptz `json:"linked_at"`
	LastInteractionAt    pgtype.Timestamptz `json:"last_interaction_at"`
}

type CustomersContact struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	MiddleName pgtype.Text        `json:"middle_name"`
	Position   pgtype.Text        `json:"position"`
	Department pgtype.Text        `json:"department"`
	Email      pgtype.Text        `json:"email"`
	Phone      pgtype.Text        `json:"phone"`
	Mobile     pgtype.Text        `json:"mobile"`
	IsPrimary  pgtype.Bool        `json:"is_primary"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	IsDeleted  pgtype.Bool        `json:"is_deleted"`
}

type EducationBalanceAccount struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	Balance      pgtype.Int4        `json:"balance"`
	CurrencyType pgtype.Text        `json:"currency_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EducationBalanceTransaction struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	StudentID           pgtype.UUID        `json:"student_id"`
	TransactionType     string             `json:"transaction_type"`
	Amount              int32              `json:"amount"`
	BalanceBefore       int32              `json:"balance_before"`
	BalanceAfter        int32              `json:"balance_after"`
	RelatedLessonID     pgtype.UUID        `json:"related_lesson_id"`
	RelatedPackageID    pgtype.UUID        `json:"related_package_id"`
	RelatedEnrollmentID pgtype.UUID        `json:"related_enrollment_id"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
}

type EducationGroup struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	LocationID    pgtype.UUID        `json:"location_id"`
	ParentGroupID pgtype.UUID        `json:"parent_group_id"`
	Name          string             `json:"name"`
	GroupType     pgtype.Text        `json:"group_type"`
	Description   pgtype.Text        `json:"description"`
	Color         pgtype.Text        `json:"color"`
	IsActive      pgtype.Bool        `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IsDeleted     pgtype.Bool        `json:"is_deleted"`
}

type EducationGroupStudent struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	StudentID  pgtype.UUID        `json:"student_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
	Status     pgtype.Text        `json:"status"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EducationLesson struct {
	ID                 pgtype.UUID        `json:"id"`
	ProfileID          pgtype.UUID        `json:"profile_id"`
	TemplateID         pgtype.UUID        `json:"template_id"`
	SubjectID          pgtype.UUID        `json:"subject_id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	TeacherID          pgtype.UUID        `json:"teacher_id"`
	LessonDate         pgtype.Date        `json:"lesson_date"`
	StartTime          pgtype.Time        `json:"start_time"`
	EndTime            pgtype.Time        `json:"end_time"`
	RoomID             pgtype.UUID        `json:"room_id"`
	MaxStudents        pgtype.Int4        `json:"max_students"`
	Status             pgtype.Text        `json:"status"`
	Price              pgtype.Numeric     `json:"price"`
	ChargeOnAttendance pgtype.Bool        `json:"charge_on_attendance"`
	ChargeOnAbsence    pgtype.Bool        `json:"charge_on_absence"`
	PaymentRequired    pgtype.Bool        `json:"payment_required"`
	Notes              pgtype.Text        `json:"notes"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	IsDeleted          pgtype.Bool        `json:"is_deleted"`
	AutoEnrollGroup    pgtype.Bool        `json:"auto_enroll_group"`
}

type EducationLessonEnrollment struct {
	ID                 pgtype.UUID        `json:"id"`
	ProfileID          pgtype.UUID        `json:"profile_id"`
	LessonID           pgtype.UUID        `json:"lesson_id"`
	StudentID          pgtype.UUID        `json:"student_id"`
	Status             pgtype.Text        `json:"status"`
	RegisteredAt       pgtype.Timestamptz `json:"registered_at"`
	AttendanceMarkedAt pgtype.Timestamptz `json:"attendance_marked_at"`
	MarkedBy           pgtype.UUID        `json:"marked_by"`
	Notes              pgtype.Text        `json:"notes"`
	WasCharged         pgtype.Bool        `json:"was_charged"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type EducationPackage struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	LessonsCount int32              `json:"lessons_count"`
	Price        pgtype.Numeric     `json:"price"`
	ValidityDays pgtype.Int4        `json:"validity_days"`
	Subjects     []byte             `json:"subjects"`
	Groups       []byte             `json:"groups"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    pgtype.Bool        `json:"is_deleted"`
}

type EducationPackagePurchase struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	PackageID      pgtype.UUID        `json:"package_id"`
	LessonsGranted int32              `json:"lessons_granted"`
	LessonsUsed    pgtype.Int4        `json:"lessons_used"`
	PricePaid      pgtype.Numeric     `json:"price_paid"`
	PurchasedAt    pgtype.Timestamptz `json:"purchased_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Status         pgtype.Text        `json:"status"`
	PaymentStatus  pgtype.Text        `json:"payment_status"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

type EducationScheduleTemplate struct {
	ID                 pgtype.UUID        `json:"id"`
	ProfileID          pgtype.UUID        `json:"profile_id"`
	Name               string             `json:"name"`
	SubjectID          pgtype.UUID        `json:"subject_id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	TeacherID          pgtype.UUID        `json:"teacher_id"`
	DayOfWeek          int32              `json:"day_of_week"`
	StartTime          pgtype.Time        `json:"start_time"`
	EndTime            pgtype.Time        `json:"end_time"`
	RoomID             pgtype.UUID        `json:"room_id"`
	ValidFrom          pgtype.Date        `json:"valid_from"`
	ValidUntil         pgtype.Date        `json:"valid_until"`
	WeekPattern        pgtype.Text        `json:"week_pattern"`
	CustomWeeks        []byte             `json:"custom_weeks"`
	Price              pgtype.Numeric     `json:"price"`
	ChargeOnAttendance pgtype.Bool        `json:"charge_on_attendance"`
	ChargeOnAbsence    pgtype.Bool        `json:"charge_on_absence"`
	PaymentRequired    pgtype.Bool        `json:"payment_required"`
	IsActive           pgtype.Bool        `json:"is_active"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	IsDeleted          pgtype.Bool        `json:"is_deleted"`
	AutoEnrollGroup    pgtype.Bool        `json:"auto_enroll_group"`
}

type EducationSubject struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsDeleted   pgtype.Bool        `json:"is_deleted"`
}

type Event struct {
	ID                   pgtype.UUID        `json:"id"`
	ProfileID            pgtype.UUID        `json:"profile_id"`
	VenueID              pgtype.UUID        `json:"venue_id"`
	Title                string             `json:"title"`
	Slug                 pgtype.Text        `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	ShortDescription     pgtype.Text        `json:"short_description"`
	EventType            string             `json:"event_type"`
	Category             pgtype.Text        `json:"category"`
	Tags                 []string           `json:"tags"`
	StartDate            pgtype.Timestamptz `json:"start_date"`
	EndDate              pgtype.Timestamptz `json:"end_date"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsOnline             pgtype.Bool        `json:"is_online"`
	OnlineUrl            pgtype.Text        `json:"online_url"`
	Address              pgtype.Text        `json:"address"`
	City                 pgtype.Text        `json:"city"`
	Coordinates          pgtype.Text        `json:"coordinates"`
	RegistrationRequired pgtype.Bool        `json:"registration_required"`
	RegistrationStart    pgtype.Timestamptz `json:"registration_start"`
	RegistrationEnd      pgtype.Timestamptz `json:"registration_end"`
	MaxParticipants      pgtype.Int4        `json:"max_participants"`
	AgeRestriction       pgtype.Text        `json:"age_restriction"`
	CoverImage           pgtype.Text        `json:"cover_image"`
	Gallery              []byte             `json:"gallery"`
	OrganizerName        pgtype.Text        `json:"organizer_name"`
	ContactEmail         pgtype.Text        `json:"contact_email"`
	ContactPhone         pgtype.Text        `json:"contact_phone"`
	Website              pgtype.Text        `json:"website"`
	SocialLinks          []byte             `json:"social_links"`
	Status               string             `json:"status"`
	Visibility           string             `json:"visibility"`
	CustomFields         []byte             `json:"custom_fields"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	Stage                pgtype.Text        `json:"stage"`
	PaymentFormID        pgtype.UUID        `json:"payment_form_id"`
}

type EventRegistration struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	EventID         pgtype.UUID        `json:"event_id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	TicketOrderID   pgtype.UUID        `json:"ticket_order_id"`
	Name            string             `json:"name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	Company         pgtype.Text        `json:"company"`
	Position        pgtype.Text        `json:"position"`
	Status          string             `json:"status"`
	CheckedInAt     pgtype.Timestamptz `json:"checked_in_at"`
	QrCode          pgtype.Text        `json:"qr_code"`
	Notes           pgtype.Text        `json:"notes"`
	Answers         []byte             `json:"answers"`
	CustomFields    []byte             `json:"custom_fields"`
	RegisteredAt    pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	VkID            pgtype.Int8        `json:"vk_id"`
	VkFirstName     pgtype.Text        `json:"vk_first_name"`
	VkLastName      pgtype.Text        `json:"vk_last_name"`
	VkPhotoUrl      pgtype.Text        `json:"vk_photo_url"`
	VkConfirmedAt   pgtype.Timestamptz `json:"vk_confirmed_at"`
	VkMessageSentAt pgtype.Timestamptz `json:"vk_message_sent_at"`
	VkMessageStatus pgtype.Text        `json:"vk_message_status"`
}

type EventReview struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	EventID        pgtype.UUID        `json:"event_id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	RegistrationID pgtype.UUID        `json:"registration_id"`
	Rating         int32              `json:"rating"`
	Title          pgtype.Text        `json:"title"`
	Text           pgtype.Text        `json:"text"`
	Photos         []string           `json:"photos"`
	IsVerified     pgtype.Bool        `json:"is_verified"`
	IsPublished    pgtype.Bool        `json:"is_published"`
	Reply          pgtype.Text        `json:"reply"`
	RepliedAt      pgtype.Timestamptz `json:"replied_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EventSchedule struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Location     pgtype.Text        `json:"location"`
	BlockType    pgtype.Text        `json:"block_type"`
	SpeakerIds   []pgtype.UUID      `json:"speaker_ids"`
	OrderIndex   pgtype.Int4        `json:"order_index"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EventSponsor struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	Name         string             `json:"name"`
	Logo         pgtype.Text        `json:"logo"`
	Website      pgtype.Text        `json:"website"`
	Description  pgtype.Text        `json:"description"`
	Tier         string             `json:"tier"`
	OrderIndex   pgtype.Int4        `json:"order_index"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type GroomingService struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	PetID           pgtype.UUID        `json:"pet_id"`
	AppointmentID   pgtype.UUID        `json:"appointment_id"`
	ServiceType     []string           `json:"service_type"`
	SpecialRequests pgtype.Text        `json:"special_requests"`
	BeforePhotoUrl  pgtype.Text        `json:"before_photo_url"`
	AfterPhotoUrl   pgtype.Text        `json:"after_photo_url"`
	GroomerID       pgtype.UUID        `json:"groomer_id"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	CustomFields    []byte             `json:"custom_fields"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type HotelBooking struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	PetID               pgtype.UUID        `json:"pet_id"`
	RoomID              pgtype.UUID        `json:"room_id"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	CheckInDate         pgtype.Date        `json:"check_in_date"`
	CheckOutDate        pgtype.Date        `json:"check_out_date"`
	ActualCheckIn       pgtype.Timestamptz `json:"actual_check_in"`
	ActualCheckOut      pgtype.Timestamptz `json:"actual_check_out"`
	Status              string             `json:"status"`
	FeedingInstructions pgtype.Text        `json:"feeding_instructions"`
	FeedingSchedule     pgtype.Text        `json:"feeding_schedule"`
	MedicationSchedule  pgtype.Text        `json:"medication_schedule"`
	SpecialRequirements pgtype.Text        `json:"special_requirements"`
	AdditionalServices  []string           `json:"additional_services"`
	TotalPrice          pgtype.Numeric     `json:"total_price"`
	DepositAmount       pgtype.Numeric     `json:"deposit_amount"`
	DepositPaid         pgtype.Bool        `json:"deposit_paid"`
	Notes               pgtype.Text        `json:"notes"`
	CustomFields        []byte             `json:"custom_fields"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
}

type HotelRoom struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	RoomNumber   string             `json:"room_number"`
	RoomType     string             `json:"room_type"`
	Capacity     int32              `json:"capacity"`
	SizeCategory pgtype.Text        `json:"size_category"`
	Description  pgtype.Text        `json:"description"`
	Amenities    []string           `json:"amenities"`
	PricePerDay  pgtype.Numeric     `json:"price_per_day"`
	IsAvailable  pgtype.Bool        `json:"is_available"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Match struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	VenueID          pgtype.UUID        `json:"venue_id"`
	Team1ID          pgtype.UUID        `json:"team1_id"`
	Team2ID          pgtype.UUID        `json:"team2_id"`
	Participant1ID   pgtype.UUID        `json:"participant1_id"`
	Participant2ID   pgtype.UUID        `json:"participant2_id"`
	Round            pgtype.Text        `json:"round"`
	Stage            pgtype.Text        `json:"stage"`
	GroupName        pgtype.Text        `json:"group_name"`
	MatchNumber      pgtype.Int4        `json:"match_number"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Location         pgtype.Text        `json:"location"`
	Score1           pgtype.Int4        `json:"score1"`
	Score2           pgtype.Int4        `json:"score2"`
	WinnerID         pgtype.UUID        `json:"winner_id"`
	IsDraw           pgtype.Bool        `json:"is_draw"`
	IsWalkover       pgtype.Bool        `json:"is_walkover"`
	Details          []byte             `json:"details"`
	Status           string             `json:"status"`
	BracketPosition  pgtype.Int4        `json:"bracket_position"`
	NextMatchID      pgtype.UUID        `json:"next_match_id"`
	LoserNextMatchID pgtype.UUID        `json:"loser_next_match_id"`
	StreamUrl        pgtype.Text        `json:"stream_url"`
	CustomFields     []byte             `json:"custom_fields"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	EntityType    pgtype.Text        `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod string             `json:"payment_method"`
	Status        string             `json:"status"`
	ExternalID    pgtype.Text        `json:"external_id"`
	ExternalData  []byte             `json:"external_data"`
	Description   pgtype.Text        `json:"description"`
	Notes         pgtype.Text        `json:"notes"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

type PaymentForm struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Fields      []byte             `json:"fields"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	Settings    []byte             `json:"settings"`
}

type PaymentGateway struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	GatewayType pgtype.Text        `json:"gateway_type"`
	Name        string             `json:"name"`
	ShopID      pgtype.Text        `json:"shop_id"`
	SecretKey   pgtype.Text        `json:"secret_key"`
	IsTestMode  pgtype.Bool        `json:"is_test_mode"`
	IsActive    pgtype.Bool        `json:"is_active"`
	WebhookUrl  pgtype.Text        `json:"webhook_url"`
	Settings    []byte             `json:"settings"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

type PaymentOrder struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	EntityType       pgtype.Text        `json:"entity_type"`
	EntityID         pgtype.UUID        `json:"entity_id"`
	PaymentFormID    pgtype.UUID        `json:"payment_form_id"`
	FormData         []byte             `json:"form_data"`
	PaymentGatewayID pgtype.UUID        `json:"payment_gateway_id"`
	PayerEmail       pgtype.Text        `json:"payer_email"`
	PayerPhone       pgtype.Text        `json:"payer_phone"`
	Amount           pgtype.Numeric     `json:"amount"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	ExternalID       pgtype.Text        `json:"external_id"`
	PaymentUrl       pgtype.Text        `json:"payment_url"`
	ExternalData     []byte             `json:"external_data"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
}

type Product struct {
	ID                pgtype.UUID        `json:"id"`
	ProfileID         pgtype.UUID        `json:"profile_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	Type              string             `json:"type"`
	Sku               pgtype.Text        `json:"sku"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	ShortDescription  pgtype.Text        `json:"short_description"`
	Price             pgtype.Numeric     `json:"price"`
	Currency          pgtype.Text        `json:"currency"`
	ImageUrl          pgtype.Text        `json:"image_url"`
	Images            []byte             `json:"images"`
	DurationMinutes   pgtype.Int4        `json:"duration_minutes"`
	BufferTimeMinutes pgtype.Int4        `json:"buffer_time_minutes"`
	StockQuantity     pgtype.Numeric     `json:"stock_quantity"`
	TrackInventory    pgtype.Bool        `json:"track_inventory"`
	LowStockThreshold pgtype.Numeric     `json:"low_stock_threshold"`
	Unit              pgtype.Text        `json:"unit"`
	MinQuantity       pgtype.Numeric     `json:"min_quantity"`
	Weight            pgtype.Numeric     `json:"weight"`
	Status            pgtype.Text        `json:"status"`
	IsFeatured        pgtype.Bool        `json:"is_featured"`
	Tags              []byte             `json:"tags"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	IsDeleted         pgtype.Bool        `json:"is_deleted"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ProductsCategory struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	SortOrder   pgtype.Int4        `json:"sort_order"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	IsDeleted   pgtype.Bool        `json:"is_deleted"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProductsSpecialist struct {
	ID             pgtype.UUID        `json:"id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	SpecialistID   pgtype.UUID        `json:"specialist_id"`
	CustomPrice    pgtype.Numeric     `json:"custom_price"`
	CustomDuration pgtype.Int4        `json:"custom_duration"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProductsVariant struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	Name          string             `json:"name"`
	Sku           pgtype.Text        `json:"sku"`
	PriceModifier pgtype.Numeric     `json:"price_modifier"`
	StockQuantity pgtype.Numeric     `json:"stock_quantity"`
	IsDefault     pgtype.Bool        `json:"is_default"`
	Attributes    []byte             `json:"attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IsDeleted     pgtype.Bool        `json:"is_deleted"`
}

type ProfileSetting struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	PublicSettings  []byte             `json:"public_settings"`
	PrivateSettings []byte             `json:"private_settings"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PromoCode struct {
	ID                 pgtype.UUID        `json:"id"`
	ProfileID          pgtype.UUID        `json:"profile_id"`
	Code               string             `json:"code"`
	Description        pgtype.Text        `json:"description"`
	DiscountType       string             `json:"discount_type"`
	DiscountValue      pgtype.Numeric     `json:"discount_value"`
	MaxUses            pgtype.Int4        `json:"max_uses"`
	UsedCount          pgtype.Int4        `json:"used_count"`
	MaxUsesPerCustomer pgtype.Int4        `json:"max_uses_per_customer"`
	MinOrderAmount     pgtype.Numeric     `json:"min_order_amount"`
	ValidFrom          pgtype.Timestamptz `json:"valid_from"`
	ValidUntil         pgtype.Timestamptz `json:"valid_until"`
	TicketTypeIds      []pgtype.UUID      `json:"ticket_type_ids"`
	IsActive           pgtype.Bool        `json:"is_active"`
	CustomFields       []byte             `json:"custom_fields"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RealEstateApartment struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	BuildingID    pgtype.UUID        `json:"building_id"`
	Number        string             `json:"number"`
	Floor         pgtype.Int4        `json:"floor"`
	RoomsCount    int32              `json:"rooms_count"`
	TotalArea     pgtype.Numeric     `json:"total_area"`
	LivingArea    pgtype.Numeric     `json:"living_area"`
	KitchenArea   pgtype.Numeric     `json:"kitchen_area"`
	LayoutType    pgtype.Text        `json:"layout_type"`
	FinishingType pgtype.Text        `json:"finishing_type"`
	Price         pgtype.Numeric     `json:"price"`
	PricePerSqm   pgtype.Numeric     `json:"price_per_sqm"`
	Status        string             `json:"status"`
	ViewType      pgtype.Text        `json:"view_type"`
	HasBalcony    pgtype.Bool        `json:"has_balcony"`
	CeilingHeight pgtype.Numeric     `json:"ceiling_height"`
	Photos        []byte             `json:"photos"`
	CustomFields  []byte             `json:"custom_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

type RealEstateBooking struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	ApartmentID   pgtype.UUID        `json:"apartment_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	BookingDate   pgtype.Timestamptz `json:"booking_date"`
	ExpiryDate    pgtype.Timestamptz `json:"expiry_date"`
	BookingAmount pgtype.Numeric     `json:"booking_amount"`
	IsPaid        pgtype.Bool        `json:"is_paid"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

type RealEstateBuilding struct {
	ID                pgtype.UUID        `json:"id"`
	ProfileID         pgtype.UUID        `json:"profile_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	Number            pgtype.Text        `json:"number"`
	FloorsCount       pgtype.Int4        `json:"floors_count"`
	EntrancesCount    pgtype.Int4        `json:"entrances_count"`
	BuildingType      pgtype.Text        `json:"building_type"`
	Status            string             `json:"status"`
	CompletionQuarter pgtype.Text        `json:"completion_quarter"`
	Photos            []byte             `json:"photos"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RealEstateDeal struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	ApartmentID      pgtype.UUID        `json:"apartment_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	DealDate         pgtype.Timestamptz `json:"deal_date"`
	ContractNumber   pgtype.Text        `json:"contract_number"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	DealType         string             `json:"deal_type"`
	Status           string             `json:"status"`
	ContractDate     pgtype.Date        `json:"contract_date"`
	RegistrationDate pgtype.Date        `json:"registration_date"`
	Notes            pgtype.Text        `json:"notes"`
	InternalNotes    pgtype.Text        `json:"internal_notes"`
	CustomFields     []byte             `json:"custom_fields"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
}

type RealEstateDocument struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	DealID       pgtype.UUID        `json:"deal_id"`
	DocumentType string             `json:"document_type"`
	FileUrl      string             `json:"file_url"`
	FileName     string             `json:"file_name"`
	FileSize     pgtype.Int8        `json:"file_size"`
	UploadedAt   pgtype.Timestamptz `json:"uploaded_at"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
}

type RealEstatePayment struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	PaymentDate   pgtype.Date        `json:"payment_date"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentType   string             `json:"payment_type"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	Status        string             `json:"status"`
	ReceiptNumber pgtype.Text        `json:"receipt_number"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

type RealEstateProject struct {
	ID                pgtype.UUID        `json:"id"`
	ProfileID         pgtype.UUID        `json:"profile_id"`
	Name              string             `json:"name"`
	Slug              pgtype.Text        `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	ProjectType       string             `json:"project_type"`
	Address           pgtype.Text        `json:"address"`
	City              pgtype.Text        `json:"city"`
	District          pgtype.Text        `json:"district"`
	Coordinates       pgtype.Text        `json:"coordinates"`
	StartDate         pgtype.Date        `json:"start_date"`
	CompletionDate    pgtype.Date        `json:"completion_date"`
	CompletionQuarter pgtype.Text        `json:"completion_quarter"`
	DeveloperCompany  pgtype.Text        `json:"developer_company"`
	DeveloperLicense  pgtype.Text        `json:"developer_license"`
	Status            string             `json:"status"`
	Infrastructure    []string           `json:"infrastructure"`
	TotalBuildings    pgtype.Int4        `json:"total_buildings"`
	TotalApartments   pgtype.Int4        `json:"total_apartments"`
	ParkingSpaces     pgtype.Int4        `json:"parking_spaces"`
	Photos            []byte             `json:"photos"`
	DocumentsUrl      pgtype.Text        `json:"documents_url"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
}

type ShortLink struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SpacesLocation struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Address       pgtype.Text        `json:"address"`
	City          pgtype.Text        `json:"city"`
	PostalCode    pgtype.Text        `json:"postal_code"`
	Country       pgtype.Text        `json:"country"`
	Latitude      pgtype.Text        `json:"latitude"`
	Longitude     pgtype.Text        `json:"longitude"`
	Phone         pgtype.Text        `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	ContactPerson pgtype.Text        `json:"contact_person"`
	IsMain        pgtype.Bool        `json:"is_main"`
	IsActive      pgtype.Bool        `json:"is_active"`
	WorkingHours  []byte             `json:"working_hours"`
	Amenities     []byte             `json:"amenities"`
	Photos        []byte             `json:"photos"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	IsDeleted     pgtype.Bool        `json:"is_deleted"`
}

type SpacesRoom struct {
	ID                 pgtype.UUID        `json:"id"`
	ProfileID          pgtype.UUID        `json:"profile_id"`
	LocationID         pgtype.UUID        `json:"location_id"`
	Name               string             `json:"name"`
	RoomNumber         pgtype.Text        `json:"room_number"`
	Description        pgtype.Text        `json:"description"`
	RoomType           pgtype.Text        `json:"room_type"`
	Floor              pgtype.Int4        `json:"floor"`
	Area               pgtype.Float8      `json:"area"`
	Capacity           pgtype.Int4        `json:"capacity"`
	Equipment          []byte             `json:"equipment"`
	Amenities          []byte             `json:"amenities"`
	IsAccessible       pgtype.Bool        `json:"is_accessible"`
	IsActive           pgtype.Bool        `json:"is_active"`
	IsBookable         pgtype.Bool        `json:"is_bookable"`
	MinBookingDuration pgtype.Int4        `json:"min_booking_duration"`
	MaxBookingDuration pgtype.Int4        `json:"max_booking_duration"`
	Color              pgtype.Text        `json:"color"`
	Photos             []byte             `json:"photos"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	IsDeleted          pgtype.Bool        `json:"is_deleted"`
}

type SpacesRoomBlock struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	RoomID        pgtype.UUID        `json:"room_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	Reason        string             `json:"reason"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

type SpacesRoomSchedule struct {
	ID        pgtype.UUID        `json:"id"`
	ProfileID pgtype.UUID        `json:"profile_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	DayOfWeek int32              `json:"day_of_week"`
	StartTime pgtype.Time        `json:"start_time"`
	EndTime   pgtype.Time        `json:"end_time"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Speaker struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Name         string             `json:"name"`
	Title        pgtype.Text        `json:"title"`
	Company      pgtype.Text        `json:"company"`
	Bio          pgtype.Text        `json:"bio"`
	Photo        pgtype.Text        `json:"photo"`
	Email        pgtype.Text        `json:"email"`
	Website      pgtype.Text        `json:"website"`
	SocialLinks  []byte             `json:"social_links"`
	Role         string             `json:"role"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Specialist struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	SecondName     pgtype.Text        `json:"second_name"`
	DisplayName    pgtype.Text        `json:"display_name"`
	Phone          pgtype.Text        `json:"phone"`
	Email          pgtype.Text        `json:"email"`
	Telegram       pgtype.Text        `json:"telegram"`
	Vk             pgtype.Text        `json:"vk"`
	Whatsapp       pgtype.Text        `json:"whatsapp"`
	Website        pgtype.Text        `json:"website"`
	Position       pgtype.Text        `json:"position"`
	Specialization pgtype.Text        `json:"specialization"`
	Status         pgtype.Text        `json:"status"`
	Color          pgtype.Text        `json:"color"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	IsDeleted      pgtype.Bool        `json:"is_deleted"`
	CustomFields   []byte             `json:"custom_fields"`
	AccountID      pgtype.UUID        `json:"account_id"`
}

// Регулярное расписание работы специалистов по дням недели
type SpecialistsSchedule struct {
	ID           pgtype.UUID `json:"id"`
	ProfileID    pgtype.UUID `json:"profile_id"`
	SpecialistID pgtype.UUID `json:"specialist_id"`
	// 0=Воскресенье, 1=Понедельник, 2=Вторник, 3=Среда, 4=Четверг, 5=Пятница, 6=Суббота
	DayOfWeek int32       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	// Начало перерыва (опционально)
	BreakStartTime pgtype.Time `json:"break_start_time"`
	// Конец перерыва (опционально)
	BreakEndTime pgtype.Time        `json:"break_end_time"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Исключения из регулярного расписания (отпуска, выходные, особые дни)
type SpecialistsScheduleException struct {
	ID            pgtype.UUID `json:"id"`
	ProfileID     pgtype.UUID `json:"profile_id"`
	SpecialistID  pgtype.UUID `json:"specialist_id"`
	ExceptionDate pgtype.Date `json:"exception_date"`
	// day_off - выходной день, custom - особый график работы
	ExceptionType  string      `json:"exception_type"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	BreakStartTime pgtype.Time `json:"break_start_time"`
	BreakEndTime   pgtype.Time `json:"break_end_time"`
	// Причина исключения: отпуск, больничный, праздник и т.д.
	Reason    pgtype.Text        `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Standing struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	TeamID        pgtype.UUID        `json:"team_id"`
	GroupName     pgtype.Text        `json:"group_name"`
	Position      pgtype.Int4        `json:"position"`
	Played        pgtype.Int4        `json:"played"`
	Won           pgtype.Int4        `json:"won"`
	Drawn         pgtype.Int4        `json:"drawn"`
	Lost          pgtype.Int4        `json:"lost"`
	GoalsFor      pgtype.Int4        `json:"goals_for"`
	GoalsAgainst  pgtype.Int4        `json:"goals_against"`
	GoalDiff      pgtype.Int4        `json:"goal_diff"`
	Points        pgtype.Int4        `json:"points"`
	BonusPoints   pgtype.Int4        `json:"bonus_points"`
	PenaltyPoints pgtype.Int4        `json:"penalty_points"`
	Form          pgtype.Text        `json:"form"`
	CustomFields  []byte             `json:"custom_fields"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Talk struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	EventID         pgtype.UUID        `json:"event_id"`
	SpeakerID       pgtype.UUID        `json:"speaker_id"`
	TrackID         pgtype.UUID        `json:"track_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Language        pgtype.Text        `json:"language"`
	Level           pgtype.Text        `json:"level"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	Location        pgtype.Text        `json:"location"`
	TalkType        pgtype.Text        `json:"talk_type"`
	Status          string             `json:"status"`
	CoSpeakerIds    []pgtype.UUID      `json:"co_speaker_ids"`
	CustomFields    []byte             `json:"custom_fields"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TalkMaterial struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	TalkID       pgtype.UUID        `json:"talk_id"`
	Title        string             `json:"title"`
	MaterialType string             `json:"material_type"`
	Url          string             `json:"url"`
	FileSize     pgtype.Int4        `json:"file_size"`
	IsPublic     pgtype.Bool        `json:"is_public"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TalkProposal struct {
	ID                pgtype.UUID        `json:"id"`
	ProfileID         pgtype.UUID        `json:"profile_id"`
	EventID           pgtype.UUID        `json:"event_id"`
	SpeakerID         pgtype.UUID        `json:"speaker_id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Abstract          pgtype.Text        `json:"abstract"`
	TargetAudience    pgtype.Text        `json:"target_audience"`
	PreferredTrackID  pgtype.UUID        `json:"preferred_track_id"`
	PreferredDuration pgtype.Int4        `json:"preferred_duration"`
	TalkType          pgtype.Text        `json:"talk_type"`
	SpeakerName       pgtype.Text        `json:"speaker_name"`
	SpeakerEmail      pgtype.Text        `json:"speaker_email"`
	SpeakerBio        pgtype.Text        `json:"speaker_bio"`
	SpeakerCompany    pgtype.Text        `json:"speaker_company"`
	Status            string             `json:"status"`
	ReviewerNotes     pgtype.Text        `json:"reviewer_notes"`
	ReviewedBy        pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	TalkID            pgtype.UUID        `json:"talk_id"`
	CustomFields      []byte             `json:"custom_fields"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TalkRating struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	TalkID         pgtype.UUID        `json:"talk_id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	RegistrationID pgtype.UUID        `json:"registration_id"`
	Rating         int32              `json:"rating"`
	ContentRating  pgtype.Int4        `json:"content_rating"`
	SpeakerRating  pgtype.Int4        `json:"speaker_rating"`
	Comment        pgtype.Text        `json:"comment"`
	IsAnonymous    pgtype.Bool        `json:"is_anonymous"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TalkTrack struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Color        pgtype.Text        `json:"color"`
	Location     pgtype.Text        `json:"location"`
	OrderIndex   pgtype.Int4        `json:"order_index"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	CaptainID    pgtype.UUID        `json:"captain_id"`
	Name         string             `json:"name"`
	ShortName    pgtype.Text        `json:"short_name"`
	Logo         pgtype.Text        `json:"logo"`
	Seed         pgtype.Int4        `json:"seed"`
	GroupName    pgtype.Text        `json:"group_name"`
	Status       string             `json:"status"`
	ContactName  pgtype.Text        `json:"contact_name"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Name         string             `json:"name"`
	Nickname     pgtype.Text        `json:"nickname"`
	Number       pgtype.Int4        `json:"number"`
	Position     pgtype.Text        `json:"position"`
	Role         string             `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TelegramBot struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	BotToken       string             `json:"bot_token"`
	BotUsername    pgtype.Text        `json:"bot_username"`
	BotName        pgtype.Text        `json:"bot_name"`
	IsActive       bool               `json:"is_active"`
	WelcomeMessage pgtype.Text        `json:"welcome_message"`
	AiEnabled      bool               `json:"ai_enabled"`
	AiProvider     pgtype.Text        `json:"ai_provider"`
	AiModel        pgtype.Text        `json:"ai_model"`
	AiSystemPrompt pgtype.Text        `json:"ai_system_prompt"`
	AiTemperature  pgtype.Numeric     `json:"ai_temperature"`
	AiMaxTokens    pgtype.Int4        `json:"ai_max_tokens"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TelegramConversation struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	TelegramUserID int64              `json:"telegram_user_id"`
	ChatID         int64              `json:"chat_id"`
	Context        []byte             `json:"context"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
}

type TelegramCustomerLink struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	TelegramUserID   int64              `json:"telegram_user_id"`
	TelegramUsername pgtype.Text        `json:"telegram_username"`
	FirstName        pgtype.Text        `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	LinkedAt         pgtype.Timestamptz `json:"linked_at"`
}

type TelegramExecution struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	WorkflowID     pgtype.UUID        `json:"workflow_id"`
	TelegramUserID int64              `json:"telegram_user_id"`
	ChatID         int64              `json:"chat_id"`
	Status         string             `json:"status"`
	InputData      []byte             `json:"input_data"`
	OutputData     []byte             `json:"output_data"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type TelegramKnowledgeBase struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	SourceType string             `json:"source_type"`
	SourceID   pgtype.UUID        `json:"source_id"`
	Title      pgtype.Text        `json:"title"`
	Content    string             `json:"content"`
	Metadata   []byte             `json:"metadata"`
	Embedding  pgvector.Vector    `json:"embedding"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type TelegramMessagesLog struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	TelegramUserID int64              `json:"telegram_user_id"`
	ChatID         int64              `json:"chat_id"`
	MessageText    pgtype.Text        `json:"message_text"`
	IsFromBot      bool               `json:"is_from_bot"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TelegramWorkflow struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	WorkflowName  string             `json:"workflow_name"`
	WorkflowKey   string             `json:"workflow_key"`
	Description   pgtype.Text        `json:"description"`
	TriggerType   string             `json:"trigger_type"`
	TriggerConfig []byte             `json:"trigger_config"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	// ID бота, к которому привязан workflow
	BotID pgtype.UUID `json:"bot_id"`
}

type TelegramWorkflowEdge struct {
	ID                pgtype.UUID        `json:"id"`
	WorkflowID        pgtype.UUID        `json:"workflow_id"`
	SourceNodeID      pgtype.UUID        `json:"source_node_id"`
	TargetNodeID      pgtype.UUID        `json:"target_node_id"`
	ConditionField    pgtype.Text        `json:"condition_field"`
	ConditionOperator pgtype.Text        `json:"condition_operator"`
	ConditionValue    pgtype.Text        `json:"condition_value"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type TelegramWorkflowNode struct {
	ID            pgtype.UUID        `json:"id"`
	WorkflowID    pgtype.UUID        `json:"workflow_id"`
	NodeKey       string             `json:"node_key"`
	NodeType      string             `json:"node_type"`
	NodeLabel     pgtype.Text        `json:"node_label"`
	PositionX     pgtype.Int4        `json:"position_x"`
	PositionY     pgtype.Int4        `json:"position_y"`
	Config        []byte             `json:"config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CredentialsID pgtype.UUID        `json:"credentials_id"`
}

type TelegramWorkflowSchedule struct {
	ID             pgtype.UUID        `json:"id"`
	WorkflowID     pgtype.UUID        `json:"workflow_id"`
	CronExpression string             `json:"cron_expression"`
	Timezone       pgtype.Text        `json:"timezone"`
	IsActive       bool               `json:"is_active"`
	LastRunAt      pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Ticket struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	TicketTypeID  pgtype.UUID        `json:"ticket_type_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	SeatID        pgtype.UUID        `json:"seat_id"`
	QrCode        string             `json:"qr_code"`
	Barcode       pgtype.Text        `json:"barcode"`
	Price         pgtype.Numeric     `json:"price"`
	AttendeeName  pgtype.Text        `json:"attendee_name"`
	AttendeeEmail pgtype.Text        `json:"attendee_email"`
	AttendeePhone pgtype.Text        `json:"attendee_phone"`
	Status        string             `json:"status"`
	CheckedInAt   pgtype.Timestamptz `json:"checked_in_at"`
	CheckedInBy   pgtype.UUID        `json:"checked_in_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TicketOrder struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	OrderNumber    string             `json:"order_number"`
	BuyerName      pgtype.Text        `json:"buyer_name"`
	BuyerEmail     pgtype.Text        `json:"buyer_email"`
	BuyerPhone     pgtype.Text        `json:"buyer_phone"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	Status         string             `json:"status"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
	PaymentID      pgtype.Text        `json:"payment_id"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	PromoCodeID    pgtype.UUID        `json:"promo_code_id"`
	Notes          pgtype.Text        `json:"notes"`
	CustomFields   []byte             `json:"custom_fields"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TicketSession struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	VenueID      pgtype.UUID        `json:"venue_id"`
	Title        pgtype.Text        `json:"title"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Capacity     pgtype.Int4        `json:"capacity"`
	SoldCount    pgtype.Int4        `json:"sold_count"`
	Status       string             `json:"status"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TicketType struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Price        pgtype.Numeric     `json:"price"`
	MaxPerOrder  pgtype.Int4        `json:"max_per_order"`
	MinPerOrder  pgtype.Int4        `json:"min_per_order"`
	IsActive     pgtype.Bool        `json:"is_active"`
	OrderIndex   pgtype.Int4        `json:"order_index"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TournamentsSetting struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	Format           string             `json:"format"`
	RoundsCount      pgtype.Int4        `json:"rounds_count"`
	GroupsCount      pgtype.Int4        `json:"groups_count"`
	TeamsPerGroup    pgtype.Int4        `json:"teams_per_group"`
	AdvanceFromGroup pgtype.Int4        `json:"advance_from_group"`
	PointsWin        pgtype.Int4        `json:"points_win"`
	PointsDraw       pgtype.Int4        `json:"points_draw"`
	PointsLoss       pgtype.Int4        `json:"points_loss"`
	Legs             pgtype.Int4        `json:"legs"`
	ThirdPlaceMatch  pgtype.Bool        `json:"third_place_match"`
	SeedingEnabled   pgtype.Bool        `json:"seeding_enabled"`
	CustomFields     []byte             `json:"custom_fields"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	Name            string             `json:"name"`
	Slug            pgtype.Text        `json:"slug"`
	Description     pgtype.Text        `json:"description"`
	Address         pgtype.Text        `json:"address"`
	City            pgtype.Text        `json:"city"`
	Coordinates     pgtype.Text        `json:"coordinates"`
	Capacity        pgtype.Int4        `json:"capacity"`
	AreaSqm         pgtype.Numeric     `json:"area_sqm"`
	Amenities       []string           `json:"amenities"`
	Equipment       []string           `json:"equipment"`
	ContactPhone    pgtype.Text        `json:"contact_phone"`
	ContactEmail    pgtype.Text        `json:"contact_email"`
	Photos          []byte             `json:"photos"`
	VirtualTourUrl  pgtype.Text        `json:"virtual_tour_url"`
	PricePerHour    pgtype.Numeric     `json:"price_per_hour"`
	PricePerDay     pgtype.Numeric     `json:"price_per_day"`
	MinBookingHours pgtype.Int4        `json:"min_booking_hours"`
	IsActive        pgtype.Bool        `json:"is_active"`
	CustomFields    []byte             `json:"custom_fields"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

type VenueBooking struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	VenueID        pgtype.UUID        `json:"venue_id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Title          pgtype.Text        `json:"title"`
	Description    pgtype.Text        `json:"description"`
	ExpectedGuests pgtype.Int4        `json:"expected_guests"`
	Status         string             `json:"status"`
	TotalPrice     pgtype.Numeric     `json:"total_price"`
	DepositAmount  pgtype.Numeric     `json:"deposit_amount"`
	DepositPaid    pgtype.Bool        `json:"deposit_paid"`
	ContactName    pgtype.Text        `json:"contact_name"`
	ContactPhone   pgtype.Text        `json:"contact_phone"`
	ContactEmail   pgtype.Text        `json:"contact_email"`
	Notes          pgtype.Text        `json:"notes"`
	InternalNotes  pgtype.Text        `json:"internal_notes"`
	CustomFields   []byte             `json:"custom_fields"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

type VenueSeat struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	VenueID      pgtype.UUID        `json:"venue_id"`
	ZoneID       pgtype.UUID        `json:"zone_id"`
	RowNumber    pgtype.Text        `json:"row_number"`
	SeatNumber   string             `json:"seat_number"`
	PositionX    pgtype.Numeric     `json:"position_x"`
	PositionY    pgtype.Numeric     `json:"position_y"`
	Rotation     pgtype.Numeric     `json:"rotation"`
	SeatType     pgtype.Text        `json:"seat_type"`
	IsAvailable  pgtype.Bool        `json:"is_available"`
	CustomFields []byte             `json:"custom_fields"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VenueZone struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	VenueID       pgtype.UUID        `json:"venue_id"`
	Name          string             `json:"name"`
	Code          pgtype.Text        `json:"code"`
	Description   pgtype.Text        `json:"description"`
	Color         pgtype.Text        `json:"color"`
	Capacity      pgtype.Int4        `json:"capacity"`
	HasSeats      pgtype.Bool        `json:"has_seats"`
	PriceModifier pgtype.Numeric     `json:"price_modifier"`
	OrderIndex    pgtype.Int4        `json:"order_index"`
	CustomFields  []byte             `json:"custom_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type VeterinaryMedicalRecord struct {
	ID             pgtype.UUID        `json:"id"`
	ProfileID      pgtype.UUID        `json:"profile_id"`
	PetID          pgtype.UUID        `json:"pet_id"`
	AppointmentID  pgtype.UUID        `json:"appointment_id"`
	VisitDate      pgtype.Timestamptz `json:"visit_date"`
	VeterinarianID pgtype.UUID        `json:"veterinarian_id"`
	ChiefComplaint pgtype.Text        `json:"chief_complaint"`
	Examination    pgtype.Text        `json:"examination"`
	Diagnosis      pgtype.Text        `json:"diagnosis"`
	Treatment      pgtype.Text        `json:"treatment"`
	Prescriptions  []string           `json:"prescriptions"`
	NextVisitDate  pgtype.Date        `json:"next_visit_date"`
	Notes          pgtype.Text        `json:"notes"`
	Attachments    []byte             `json:"attachments"`
	CustomFields   []byte             `json:"custom_fields"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

type VeterinaryPet struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	Name            string             `json:"name"`
	Species         string             `json:"species"`
	Breed           pgtype.Text        `json:"breed"`
	Gender          pgtype.Text        `json:"gender"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	Color           pgtype.Text        `json:"color"`
	Weight          pgtype.Numeric     `json:"weight"`
	ChipNumber      pgtype.Text        `json:"chip_number"`
	PassportNumber  pgtype.Text        `json:"passport_number"`
	IsSterilized    pgtype.Bool        `json:"is_sterilized"`
	Allergies       []string           `json:"allergies"`
	ChronicDiseases []string           `json:"chronic_diseases"`
	SpecialNotes    pgtype.Text        `json:"special_notes"`
	PhotoUrl        pgtype.Text        `json:"photo_url"`
	CustomFields    []byte             `json:"custom_fields"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	IsDeleted       pgtype.Bool        `json:"is_deleted"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type VeterinaryVaccination struct {
	ID                  pgtype.UUID        `json:"id"`
	ProfileID           pgtype.UUID        `json:"profile_id"`
	PetID               pgtype.UUID        `json:"pet_id"`
	MedicalRecordID     pgtype.UUID        `json:"medical_record_id"`
	VaccineName         string             `json:"vaccine_name"`
	VaccineType         pgtype.Text        `json:"vaccine_type"`
	BatchNumber         pgtype.Text        `json:"batch_number"`
	VaccinationDate     pgtype.Date        `json:"vaccination_date"`
	NextVaccinationDate pgtype.Date        `json:"next_vaccination_date"`
	VeterinarianID      pgtype.UUID        `json:"veterinarian_id"`
	Notes               pgtype.Text        `json:"notes"`
	CustomFields        []byte             `json:"custom_fields"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
}

type VkMessageTemplate struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	ModuleCode       string             `json:"module_code"`
	TemplateKey      string             `json:"template_key"`
	TemplateName     string             `json:"template_name"`
	Description      pgtype.Text        `json:"description"`
	MessageText      string             `json:"message_text"`
	SendImmediately  pgtype.Bool        `json:"send_immediately"`
	SendDelayMinutes pgtype.Int4        `json:"send_delay_minutes"`
	TriggerEvent     pgtype.Text        `json:"trigger_event"`
	Conditions       []byte             `json:"conditions"`
	IsActive         pgtype.Bool        `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
}

type VkMessagesLog struct {
	ID                      pgtype.UUID        `json:"id"`
	ProfileID               pgtype.UUID        `json:"profile_id"`
	VkID                    int64              `json:"vk_id"`
	EntityType              string             `json:"entity_type"`
	EntityID                pgtype.UUID        `json:"entity_id"`
	TemplateID              pgtype.UUID        `json:"template_id"`
	TemplateKey             pgtype.Text        `json:"template_key"`
	MessageText             string             `json:"message_text"`
	Status                  string             `json:"status"`
	VkMessageID             pgtype.Int4        `json:"vk_message_id"`
	VkConversationMessageID pgtype.Int4        `json:"vk_conversation_message_id"`
	VkPeerID                pgtype.Int8        `json:"vk_peer_id"`
	ErrorCode               pgtype.Text        `json:"error_code"`
	ErrorMessage            pgtype.Text        `json:"error_message"`
	RetryCount              pgtype.Int4        `json:"retry_count"`
	MaxRetries              pgtype.Int4        `json:"max_retries"`
	NextRetryAt             pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SentAt                  pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
	ReadAt                  pgtype.Timestamptz `json:"read_at"`
	FailedAt                pgtype.Timestamptz `json:"failed_at"`
}

type WarehouseInventoryCount struct {
	ID            pgtype.UUID        `json:"id"`
	ProfileID     pgtype.UUID        `json:"profile_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	Status        pgtype.Text        `json:"status"`
	ScheduledDate pgtype.Timestamptz `json:"scheduled_date"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	UpdatedBy     pgtype.UUID        `json:"updated_by"`
}

type WarehouseInventoryCountItem struct {
	ID               pgtype.UUID        `json:"id"`
	InventoryCountID pgtype.UUID        `json:"inventory_count_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	ExpectedQuantity pgtype.Numeric     `json:"expected_quantity"`
	ActualQuantity   pgtype.Numeric     `json:"actual_quantity"`
	Difference       pgtype.Numeric     `json:"difference"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type WarehouseStock struct {
	ID               pgtype.UUID        `json:"id"`
	WarehouseID      pgtype.UUID        `json:"warehouse_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	ReservedQuantity pgtype.Numeric     `json:"reserved_quantity"`
	LastCountedAt    pgtype.Timestamptz `json:"last_counted_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WarehouseStockMovement struct {
	ID              pgtype.UUID        `json:"id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	MovementType    pgtype.Text        `json:"movement_type"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	FromWarehouseID pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID        `json:"to_warehouse_id"`
	ReferenceType   pgtype.Text        `json:"reference_type"`
	ReferenceID     pgtype.UUID        `json:"reference_id"`
	Price           pgtype.Numeric     `json:"price"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

type WarehouseWarehouse struct {
	ID        pgtype.UUID        `json:"id"`
	ProfileID pgtype.UUID        `json:"profile_id"`
	Name      string             `json:"name"`
	Type      pgtype.Text        `json:"type"`
	Address   pgtype.Text        `json:"address"`
	IsDefault pgtype.Bool        `json:"is_default"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	IsDeleted pgtype.Bool        `json:"is_deleted"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
